[package]
name = "prepare-input"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10"
regex = "1.10"
num-bigint = "0.4"
num-traits = "0.2"
